# Generated by Django 5.2.9 on 2025-12-17 11:36

import core.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EHRConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250)),
                ('ehr_name', models.CharField(choices=[('athena', 'Athena'), ('epic', 'EPIC'), ('eclinicalworks', 'eClinicalWorks'), ('PracticeFusion', 'Practice Fusion'), ('NextGen', 'NEXTGEN'), ('advance_md', 'ADVANCE_MD')], max_length=120)),
                ('app_type', models.CharField(choices=[('provider', 'Provider Facing Application'), ('system', 'Backend System'), ('bulk', 'Bulk Import')], max_length=50)),
                ('grant_type', models.CharField(default='client_credentials', editable=False, max_length=25)),
                ('client_id', models.CharField(blank=True, max_length=250, null=True)),
                ('client_secret', models.CharField(blank=True, max_length=250, null=True)),
                ('redirect_uri', models.URLField(blank=True, max_length=255, null=True)),
                ('auth_code_uri', models.URLField(blank=True, max_length=255, null=True)),
                ('auth_code', models.CharField(blank=True, max_length=255, null=True)),
                ('scope', models.TextField(blank=True, null=True)),
                ('audiance', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('base_url', models.URLField(blank=True, max_length=250, null=True)),
                ('token_url', models.URLField(blank=True, max_length=250, null=True)),
                ('authorize_url', models.URLField(blank=True, max_length=255, null=True)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('access_token_generated_at', models.DateTimeField(blank=True, null=True)),
                ('refresh_token_generated_at', models.DateTimeField()),
                ('practice_id', models.CharField(blank=True, max_length=100, null=True)),
                ('enterprise_id', models.CharField(blank=True, max_length=100, null=True)),
                ('site_id', models.CharField(blank=True, max_length=255, null=True)),
                ('session_id', models.TextField(blank=True, editable=False, null=True)),
                ('username', models.CharField(blank=True, max_length=250, null=True)),
                ('password', models.CharField(blank=True, max_length=250, null=True)),
                ('client_assertion', models.CharField(blank=True, max_length=2084, null=True)),
                ('ehr_environment', models.CharField(blank=True, choices=[('sandbox', 'Sandbox Environment'), ('production', 'Production Environment')], max_length=50, null=True)),
                ('connection_status', models.CharField(blank=True, choices=[('active', 'Active'), ('inative', 'Inactive')], default='active', max_length=50)),
                ('office_key', models.CharField(blank=True, max_length=8, null=True)),
                ('status_url', models.CharField(blank=True, max_length=100, null=True)),
                ('export_url', models.CharField(blank=True, max_length=100, null=True)),
                ('jobId', models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebHook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('webhook_url', models.CharField(blank=True, max_length=150, null=True)),
                ('token', models.CharField(blank=True, default=core.models.WebHook.code_generate, max_length=250, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('method', models.CharField(blank=True, choices=[('get', 'GET'), ('post', 'POST')], max_length=5, null=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ehrconnection')),
            ],
            options={
                'db_table': 'ehr_webhook',
            },
        ),
    ]
