# Generated by Django 5.2.9 on 2025-12-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_ehrconnection_auth_code_uri_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ehrconnection',
            name='department_id',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
