# Generated by Django 5.2.9 on 2026-01-15 12:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ehrconnection_department_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ehrconnection',
            name='code_challenge',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ehrconnection',
            name='code_verifier',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ehrconnection',
            name='customer_auth_url',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AddField(
            model_name='ehrconnection',
            name='org_redirect_uri',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
