# Generated by Django 5.2.9 on 2026-01-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ehrconnection_code_challenge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ehrconnection',
            name='ehr_environment',
            field=models.CharField(blank=True, choices=[('sandbox', 'Sandbox Environment'), ('production', 'Production Environment')], default='sandbox', max_length=50, null=True),
        ),
    ]
